import { cpSync, existsSync, mkdirSync, rmSync, writeFileSync } from 'node:fs'
import path from 'node:path'

const games = ['plinko', 'rasca', 'ruleta', 'hilo', 'goldentree']
const repoRoot = process.cwd()
const miniAppRoot = path.join(repoRoot, 'MiniApp')
const stagingRoot = path.join(repoRoot, '.miniapp-web-src')
const outputRoot = path.join(repoRoot, 'public', 'miniapp-web')

function assertExists(targetPath, label) {
  if (!existsSync(targetPath)) {
    throw new Error(`${label} not found: ${targetPath}`)
  }
}

function ensurePageFiles(game) {
  const gameRoot = path.join(stagingRoot, game)
  const required = ['axml', 'acss', 'js', 'json']

  for (const ext of required) {
    const filePath = path.join(gameRoot, `${game}.${ext}`)
    assertExists(filePath, `Required MiniApp file (${game}.${ext})`)
  }
}

function buildCustomRoutes() {
  return {
    '/plinko/plinko': '/plinko',
    '/rasca/rasca': '/rasca',
    '/ruleta/ruleta': '/ruleta',
    '/hilo/hilo': '/hilo',
    '/goldentree/goldentree': '/goldentree',
  }
}

function main() {
  rmSync(stagingRoot, { recursive: true, force: true })
  rmSync(outputRoot, { recursive: true, force: true })

  mkdirSync(stagingRoot, { recursive: true })

  for (const game of games) {
    const source = path.join(miniAppRoot, game)
    const destination = path.join(stagingRoot, game)
    assertExists(source, `MiniApp source directory (${game})`)
    cpSync(source, destination, { recursive: true, force: true })
  }

  writeFileSync(path.join(stagingRoot, 'app.js'), 'App({});\n', 'utf8')
  writeFileSync(path.join(stagingRoot, 'app.acss'), '/* generated by miniapp:sync */\n', 'utf8')
  writeFileSync(
    path.join(stagingRoot, 'app.json'),
    `${JSON.stringify(
      {
        pages: games.map((game) => `${game}/${game}`),
        window: {
          defaultTitle: 'MiniApp Web',
        },
        router: {
          mode: 'hash',
          customRoutes: buildCustomRoutes(),
        },
      },
      null,
      2,
    )}\n`,
    'utf8',
  )

  for (const game of games) {
    ensurePageFiles(game)
  }

  console.log(`MiniApp sync complete: ${stagingRoot}`)
}

main()
